# docker-compose.yml file
version: "3.5"

services:
  mongo_one:
    container_name: mongo1
    image: arm64v8/mongo
    command: mongod --replSet my-mongo-set

  mongo_two:
    container_name: mongo2
    image: arm64v8/mongo
    command: mongod --replSet my-mongo-set

  mongo_three:
    container_name: mongo3
    image: arm64v8/mongo
    command: mongod --replSet my-mongo-set

networks:
  default:
    external:
      name: my-mongo-cluster